# https://www.sphinx-doc.org/en/master/tutorial/deploying.html
name: 'Sphinx: Render docs'

on: push
# on:
#   push:
#     branches:
#       - 'main'
#     paths:
#       - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: docs/requirements.txt
    - run: python -m pip install --upgrade pip setuptools wheel
    - run: python -m pip install -r docs/requirements.txt
    - name: Build HTML
    - run: cd docs && make html
    #   uses: ammaraskar/sphinx-action@master
    #   with:
    #     pre-build-command: 'python -m pip install --upgrade pip setuptools wheel'
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: docs/_build/html/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html
